#ifndef ___MODEL_MODEL_ORT_H
#define ___MODEL_MODEL_ORT_H
/* Auto-generated by bin2c.py */
#include <stddef.h>

extern const unsigned char model_ort_start[];
extern const size_t model_ort_size;

#endif
